/*AULA MODELAGEM*/

 CREATE DATABASE COMERCIO;
 
 USE COMERCIO;
 
 CREATE TABLE CLIENTE(
 IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
 NOME VARCHAR (30) NOT NULL,
 SEXO ENUM('M','F') NOT NULL,
 EMAIL VARCHAR (50) UNIQUE,
 CPF VARCHAR (15) UNIQUE
 );
 
 CREATE TABLE ENDEREÇO(
 IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
 RUA VARCHAR(30) NOT NULL,
 BAIRRO VARCHAR (30) NOT NULL,
 CIDADE VARCHAR(30) NOT NULL,
 ESTADO CHAR (2) NOT NULL,
 ID_CLIENTE INT UNIQUE,
 FOREIGN KEY(ID_CLIENTE)
 REFERENCES CLIENTE(IDCLIENTE)
);

 CREATE TABLE TELEFONE(
 IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
 TIPO ENUM ('RES','COM','CEL') NOT NULL,
 NUMERO VARCHAR(10) NOT NULL,
 ID_CLIENTE INT,
 FOREIGN KEY(ID_CLIENTE)
 REFERENCES CLIENTE(IDCLIENTE)
 );

INSERT INTO CLIENTE VALUES (NULL,'JOAO','M','JOAO@HOTMAIL.COM','76580050020');
INSERT INTO CLIENTE VALUES (NULL,'ANA','F','ANA@HOTMAIL.COM','86580055040');
INSERT INTO CLIENTE VALUES (NULL,'CLARA','F',NULL,'76550020070');
INSERT INTO CLIENTE VALUES (NULL,'JORGE','M','JORGE@HOTMAIL.COM','98080553050');
INSERT INTO CLIENTE VALUES (NULL,'CELIA','F','CELIA@HOTMAIL.COM','26581055024');

SELECT * FROM CLIENTE;
+-----------+-------+------+-------------------+-------------+
| IDCLIENTE | NOME  | SEXO | EMAIL             | CPF         |
+-----------+-------+------+-------------------+-------------+
|         1 | JOAO  | M    | JOAO@HOTMAIL.COM  | 76580050020 |
|         2 | ANA   | F    | ANA@HOTMAIL.COM   | 86580055040 |
|         3 | CLARA | F    | NULL              | 76550020070 |
|         4 | JORGE | M    | JORGE@HOTMAIL.COM | 98080553050 |
|         5 | CELIA | F    | CELIA@HOTMAIL.COM | 26581055024 |
+-----------+-------+------+-------------------+-------------+

INSERT INTO ENDEREÇO VALUES (NULL,'AV COPACABANA','COPACABANA','RIO DE JANEIRO','RJ',4);
INSERT INTO ENDEREÇO VALUES (NULL,'AV NITEROI','MEDIANEIRA','PORTO ALEGRE','RS',3);
INSERT INTO ENDEREÇO VALUES (NULL,'RUA SATO ANTONIO','CHAGAS','SAO PAULO','SP',2);
INSERT INTO ENDEREÇO VALUES (NULL,'RUA ANTONIO SA','CENTRO','BELO HORIZONTE','BH',1);
INSERT INTO ENDEREÇO VALUES (NULL,'RUA CAPITAO VARGAS','FATIMA','SAO PAULO','SP',5);


INSERT INTO TELEFONE VALUES (NULL,'RES','5133874561',5);
INSERT INTO TELEFONE VALUES (NULL,'COME','5199654530',4);
INSERT INTO TELEFONE VALUES (NULL,'CEL', '51998817023',2);
INSERT INTO TELEFONE VALUES (NULL,'COM', '51999817024',2);
INSERT INTO TELEFONE VALUES (NULL,'RES', '5133155261',2);
INSERT INTO TELEFONE VALUES (NULL,'RES','553354530',4);
INSERT INTO TELEFONE VALUES (NULL,'CEL','5899995664',1);
